macros.lua

If a python subpackage had "BuildArch: noarch" (as is usually done
for -doc subpackages), the generated subpackage didn't include that
line, so different architectures were used for python and python3
packages.

Copy BuildArch from subpackages

---

macros.lua

RPM 4.14 became much stricter in validating options in macros...

Fix macros for usage with RPM 4.14

---

macros.lua

RPM 4.14 became strict and no longer allows calling macros with unknown
parameters. Previous RPM versions had already printed this as warnings
in the build log, but this was easily missed.
Commit 0ee2f5 was only partially fixing the issues observed.

Further fixes for RPM 4.14

---

macros.lua

without this rpm default to 0 as epoch which fails comparison with
packages having lower version but higher epoch

add epoch while printing "Provides:"

---

macros/010-common-defs

Add ``%pytest`` and ``%pytest_arch`` macros as described in https://lists.opensuse.org/opensuse-python/2019-02/msg00005.html

Add pytest definitions.

---

macros/010-common-defs

Every use of single-spec macros build in the extra directory called ``_build.%{python_flavor}``. This change extends pytest call to ignore all of them when running the tests.

Add --ignore to pytest calls to ignore build directories.

---

macros/010-common-defs

While rewriting the macro in Lua, we have lost use of already existing ``$PYTHONPATH`` environmental variable.

Yet another attempt to preserve $PYTHONPATH set in the environment.

---

macros/010-common-defs

Fixes bsc#1094323
CC: @bmwiedemann

%pyproject_install macro should include --no-compile.

---

macros/010-common-defs

several packages did not build reproducibly because tests wrote
time-based .pyc files that differed for every build.
See https://reproducible-builds.org/ for why this matters.
One current example is our `python-enaml` Tumbleweed package.

Do not write .pyc files for tests

---

macros/010-common-defs

(for %pytest* and %pyproject* macros)
Also, write them in multiline more readable manner.
If anybody refactor shared code to special function/macro, I am all ears.

Do not expand macros, just print them unexpanded

---

macros/010-common-defs

Expanding PYTHONPATH by the Lua macro is too early, PYTHONPATH set during `%check` before calling `%pytest*` is overridden as in the posted log from python-numpy https://github.com/openSUSE/python-rpm-macros/issues/48#issuecomment-648104068
Fixes #48 a bit more

let the shell expand PYTHONPATH in pytest macros

---

macros/010-common-defs

Leap 15.1 and 15.2 repositories fail to expand the pytest_arch. I am not entirely sure why, but adding the blank line seems to help.
Compare python-numpy in [devel:languages:python:numeric](https://build.opensuse.org/package/show/devel:languages:python:numeric/python-numpy) with [home:bnavigator:branches:devel:languages:python:numeric](https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python:numeric/python-numpy) where I have branched python-rpm-macros into the project and [applied the patch](https://build.opensuse.org/package/rdiff/home:bnavigator:branches:devel:languages:python:numeric/python-rpm-macros?opackage=python-rpm-macros&oproject=devel%3Alanguages%3Apython%3AFactory&rev=2).

add blank line between pytest and pytest_arch

---

macros/010-common-defs

With the firm deprecation of python setup.py test, a lot of packages are
moving to calling python -m unittest for their testsuite, to avoid a lot
of duplicated and slightly different code, add two macros for ease of
calling.

Add pyunittest and pyunittest_arch macros

---

macros/010-common-defs

Including -v in the pyunittest macros makes for lovely test output, but
it also makes macro expansion fraught with peril, so drop it.
Fixes #57

Drop -v from the pyunittest macros

---

README.md
macros/010-common-defs

- Closes #9
- Closes #35
- Closes #41 (possibly)
- Restores the compilation for `%pyproject_install` removed by #37

add python_compileall macro and use it in pyproject_install

---

README.md
macros/010-common-defs

This removes the attempt of pip to check for new versions and gets rid of the warning message saying so.
```
[    4s] 1 location(s) to search for versions of pip:
[    4s] * https://pypi.org/simple/pip/
[    4s] Fetching project page and analyzing links: https://pypi.org/simple/pip/
[    4s] Getting page https://pypi.org/simple/pip/
[    4s] Found index url https://pypi.org/simple
[    4s] Getting credentials from keyring for https://pypi.org/simple
[    4s] Getting credentials from keyring for pypi.org
[    4s] Looking up "https://pypi.org/simple/pip/" in the cache
[    4s] Request header has "max_age" as 0, cache bypassed
[    4s] Starting new HTTPS connection (1): pypi.org:443
[    4s] Could not fetch URL https://pypi.org/simple/pip/: connection error: …
```

disable pip version check: no connection to pypi.org

---

macros/010-common-defs

Fixes #62 (https://github.com/openSUSE/python-rpm-macros/pull/60#issuecomment-710102219)
Works in https://build.opensuse.org/package/show/home:bnavigator:branches:devel:languages:python:Factory/python-rpm-macros

fix whitespace after escape in compileall macro

---

flavor.in
macros.lua
macros/010-common-defs

This is the `multiple_flavors.patch` from https://build.opensuse.org/request/show/842974 without the actual activation of `python36` and `python38` flavor.
Based on @mcepl's original patch, fixed for the expansion of `$python` in `%python_expand` and the macros calling `sysconfig`.

Prepare for multiple python3 flavors

---

compile-macros.sh

https://build.opensuse.org/request/show/843212#comment-1336525
@bnavigator What do you think?

Add python36 and python38 flavours.

---

macros.lua

A fix for when people need the executable as argument and use constructions like  `--python="$python"` or other shell command delimiters directly after `$python` like in https://github.com/openSUSE/python-rpm-macros/issues/66#issuecomment-715609273

more command delimiters for %python_expand

---

macros.lua
macros/010-common-defs

Latest master on [my branch of Staging:N](https://build.opensuse.org/project/show/home:bnavigator:branches:openSUSE:Factory:Staging:N), needed this early expand to not fail for e.g. in python-ordered-set. I am not sure whether an update of rpm in Factory or python36 in Staging:N triggered the now failing expansion.

More flavor expansion fixes

---

macros.lua

The current unresolvables of `python3-dateutil` in Staging:N revealed that we also need to rewrite those properties to provide, obsolete, ... the 'python3-foo' packages.

Add default provider lines for more properties

---

macros.lua

To allow constructs like
```
%define python_subpackage_only 1
%package -n %{python_flavor}-%{name}
%files %{python_files %{name}}
```

expand parameters for subpackage_only packages

---

README.md
macros.lua

We have to change the `%python_subpackage_only` logic. The use of `%package -n %{python_flavor}-foo` conflicts with the fact that we need to rewrite the tag values of the subpackage for the default provider too.

Also rewrite subpackage_only default providers

---

functions.lua
macros/010-common-defs

This is for the correct handling of f2py3 in python-numpy (https://github.com/openSUSE/python-rpm-macros/issues/66#issuecomment-734271479)

Fix python_provides for default provider

---

macros.lua

Fixes unresolvable protobuf in Staging:N (see #66), because javapackages-tools:extras currently provides python3-javapackages- with the trailing `-`.
The wrong  `.. "-" .. param` concatenation was already present with the call of old `print_obsoletes()`. I am surprised that it didn't surface in the past 4 years.

fix print_provided_flavor

---

flavor.in
macros/010-common-defs

See [home:bnavigator:branches:openSUSE:Factory:Staging:N](https://build.opensuse.org/project/show/home:bnavigator:branches:openSUSE:Factory:Staging:N) if this works or not.
[home:bnavigator:branches:devel:languages:python](https://build.opensuse.org/project/show/home:bnavigator:branches:devel:languages:python) for distro targets with older rpm.
Fixes #84

Fix python_sysconfig_ macros for rpm 4.16

---

macros/010-common-defs

This removes the annoying `sh: /usr/bin/python2: No such file or directory` error at the beginning of each rpmbuild on Tumbleweed. 
Also creates a better diagnostic for cases, when a  `%pythonXX_foo` macro that uses `%_python_sysconfig_path()`, is executed, but the interpreter of the flavor is not installed. (e.g. see current failures in build targets where the latest python-rpm-macros with more flavors is imported but the new definition of pythons in the prjconf is still missing.)

remove python2 not found error

---

buildset.in
macros.lua

New version of #88 that works both on server side and with rpm itself.
Fixes #89.
See https://build.opensuse.org/project/show/home:bnavigator:branches:devel:languages:python:Factory

Add %python pseudo-macro for %python_modules -- server and rpm version

---

macros/010-common-defs

closes #93
https://www.python.org/dev/peps/pep-0427/
https://www.python.org/dev/peps/pep-0425/
Successful build in https://build.opensuse.org/package/show/home:bnavigator:python-rpm-macros/python-pendulum

Workaround for undetected ABI and platform tags

---

macros.lua

%python_module is sometimes used for `Provides:`  tags. We cannot use boolean rpm dependencies -- including parantheses -- there:
```
[ 20s] error: line 60: No rich dependencies allowed for this type: Provides: (python36-six-doc = 1.15.0) (python38-six-doc = 1.15.0)
```
With the fix:
```
> rpm -q --provides /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/home/abuild/rpmbuild/RPMS/noarch/python-six-doc-1.15.0-0.noarch.rpm
python-six-doc = 1.15.0-0
python36-six-doc = 1.15.0
python38-six-doc = 1.15.0
```
```
[ben@skylab:~/src/osc/home:bnavigator:python-rpm-macros/python-six]% osc shell 
abuild@skylab:~> rpm --eval '%{python_module one}'
python36-one python38-one
abuild@skylab:~> rpm --eval '%{python_module one and two}'
(python36-one and two) (python38-one and two)
abuild@skylab:~> rpm --eval …
```

Only add parentheses in %python_module (_lua) when boolean operators are used.

---

README.md
buildset.in
compile-macros.sh
macros-default-pythons

Per @DimStar77's request: A local rpmbuild should be close to what happens on the build service. Provide the default buildset in python-rpm-macros like it is defined by the [Factory prjconf](https://build.opensuse.org/projects/openSUSE:Factory/prjconf).
This PR also enables the creation of macros for a `python39`, but `python39`  is not included into the buildset yet.

Sync %pythons to Factory prjconf definition

---

macros.lua
macros/010-common-defs

`%python_subpackage_only` was expanded too early through `_python_macro_init() -> _python_scan_spec()` because now `%python_module_lua()` also calls it. The prjconf override did not. Hence the necessary move to `%python_subpackages`.
Note: The python_subpackages macro seems to run into some rpm/lua line limit for macros/functions. Adding any more lines, including comments, creates an unterminated body error.
Extra: let `_python_sysconfig_*`  return a string without whitespace, so that we don't break opencv3, which uses `%python2_sitelib` as CMake parameter despite not having python2 installed.

Expand python_subpackage_only not earlier than in python_subpackages

---

buildset.in

The Leap backports do not like the default skip introduced in #97

don't define skip_python2 by default

---

README.md
macros/010-common-defs

* Too many packages are using `%pyproject_install` without `%pyproject_wheel` and are not happy with the move of the wheel file to `build/` (#94)
* SLE12 backports did not like the "mv -n"
* Expand documentation about PEP517/PEP518 macros

Fixes for PEP517/PEP518 macros

---

compile-macros.sh
default-prjconf

* This makes sure building a package directly with rpmbuild uses the same
definitions for the distribution of the host as with the build target of
the build service
See build logs of
https://build.opensuse.org/package/show/home:bnavigator:python-rpm-macros/python-rpm-macros
SLE12 backports and the sort still need to be fixed by appropriate prjconf definitions.

Read .rpmmacros (= prjconf Macro: definitions) for default buildset

---

macros/010-common-defs

I am so sorry!
The last change with correcting a syntax error was not in the #103, but in my tests on https://build.opensuse.org/package/show/home:bnavigator:python-rpm-macros/python-rpm-macros?rev=28, so I didn't notice.

fixup: last PR was missing a commit for pyproject_wheel syntax errors

---

functions.lua

Closes #109 
```
abuild@skylab:~> rpm -E '%python36_install_alternative x'
update-alternatives --quiet --install /usr/bin/x x /usr/bin/x-3.6 36
abuild@skylab:~> rpm -E '%python38_install_alternative x'
update-alternatives --quiet --install /usr/bin/x x /usr/bin/x-3.8 1038
abuild@skylab:~> rpm -E '%python39_install_alternative x'
update-alternatives --quiet --install /usr/bin/x x /usr/bin/x-3.9 39
abuild@skylab:~> rpm -E '%python3_install_alternative x'
update-alternatives --quiet --install /usr/bin/x x /usr/bin/x-3.8 38
```

increase default python3 update-alternative prio by 1000

---

macros.lua

Fixes #111:
```
[ben@skylab:…ac-rpm-runtime]% grep '^Requires:' python-testpac-rpm-runtime.spec                                                                                                                                [0]
Requires:       (python-AifB if python-B)
Requires:       (python-A36 if python36-base)
Requires:       (python-A38 if (python-base >= 3.8 with python38-base))
Requires:       (python-C and python-D and NOPY)
Requires:       (python-E and (python-F and NOPY2))
Requires:       packageand(python-A:python-B)
Requires:       packageand(python-C:D)
Requires:       packageand(E:python-F)
Requires:       python-AXY some-extra-package-on-same-line python-same-line
Requires:       tex(abcd)
Requires:       tex(abcd.xxy)
Requires:       pkgconfig(abcd) …
```

fix boolean split gh#openSUSE/python-rpm-macros#111

---

flavor.in

First trivial fix necessary for python310:
Before: 
```
rpm -E '%__python310`
/usr/bin/python31.0
```
After:
```
rpm -E '%__python310`
/usr/bin/python3.10
```

fix flavor executable substitution for python310

---

default-prjconf

Step~~s 3 and~~ 5 from https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/message/CLJG47NPQAJNTGXES7HXWVA3D3UOYSIQ/
Requires #121.
This is just the reference file. The changes only have an effect on the build service if the prjconf is updated accordingly.

Update buildset: Remove python36, add python310

---

flavor.in

rpm is invokin this via the standard /bin/sh shell which might not
be bash. use POSIX shell constructs instead.

Avoid bashism in %()

---

flavor.in

fixes a regression from #135
(see https://build.opensuse.org/request/show/990548#comment-1654781)
home:bnavigator:python-rpm-macros/python-testpac-rpm-runtime:
```specfile
%pre
%python_libalternatives_reset_alternative testbin1
%python_libalternatives_reset_alternative testbin2
%post
%python_install_alternative testbinA
%{python_install_alternative testbinB} --slave /usr/bin/testbinC testbinC /usr/bin/testbinC-%{python_bin_suffix}
%{python_install_alternative testbin1 testbin2} \
--slave /usr/bin/testbin3 testbin3 /usr/bin/testbin3-%{python_bin_suffix}
echo "another command"
%postun
%python_uninstall_alternative testbin1
echo "another command u"
```
```shell
> rpm -q --scripts /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/home/abuild/rpmbuild/RPMS/noarch/python310-testpac-rpm-runtime-0.2- …
```

restore end-of-line in alternative scriptlets

---

flavor.in

Another take at #137
Attn @dirkmueller 
```specfile
%pre
%python_libalternatives_reset_alternative testbin1
%python_libalternatives_reset_alternative testbin2
%python_libalternatives_reset_alternative testbin4
echo "another command pre"
%post
%python_install_alternative testbin1
%python_install_alternative testbin2 testbin3
echo "inbetween command post"
%if ! %{with libalternatives}
%{python_install_alternative testbin4} \
--slave /usr/bin/testbin-extra testbin-extra /usr/bin/testbin-extra-%{python_bin_suffix}
%endif
echo "another command post"
%postun
%python_uninstall_alternative testbin1
%python_uninstall_alternative testbin2
%python_uninstall_alternative testbin4
echo "another command postun"
```
without libalternatives:
```bash …
```

more compact alternative scriptlets without newline

---

functions.lua
macros.lua

Fixes #141
As usual, I have included the fixes in https://build.opensuse.org/project/show/home:bnavigator:python-rpm-macros

Allow extra parameters in section headers

---

flavor.in

The move of `%pyproject_install` from `%python_expand` to `flavor.in`, didn't consider the expansion of `%python_compileall`

fix double expanded compileall in %{$python_pyproject_install}

---

flavor.in
macros.lua
macros/010-common-defs

Fixes #150, see discussion there.
We can't use the `-s` parameter of `python -m compileall`, because we need to stay compatible with Python <3.9 for the python38 flavor and Python 3.6 in 15.x.

Strip buildroot from pyc files

---

README.md
flavor.in

As requested in #153 
This macro can be called explicitly as `%python310_fix_shebang`, if you want to have all scripts installed into `%_bindir` executed by `/usr/bin/python3.10`.
It is called implicitly in `%<flavor>_pyproject_install`, **but not in the deprecated `%<flavor>_install`.** The latter would require more effort to implement, because adding lines to the macro would prevent the common pattern to append arguments directly after the currently parameterless macro.
In a `%define pythons python3` build environment, `%python3_fix_shebang` creates the shebang with the resolved symlink where `%{_bindir}/python3` points to. This is the only use case where the macro makes sense. When installing entry-points, Pip and Setuptools normally create the interpreter lines with the same …

Add %<flavor>_fix_shebang macro

---

default-prjconf

The [Tumbleweed prjconf](https://build.opensuse.org/projects/openSUSE:Factory/prjconf) has enabled python311 now. This must be reflected in the macros for pure rpmbuild builds.
It's also probably time to switch off python38 soon.

Add python311 to buildset

---

flavor.in

The initially suggested solution for #150, implemented in #151, has impacted the build time of large python packages severely. Loading the python interpreter anew for the compilation of each source file takes a long time.
Let's move the loop into the interpreter process, so that it gets only loaded once and can use its import cache for all file compilations.
I checked the resulting `.pyc` files, there is no trace of glob order or contents of the `sys.argv[]` input to the script.
This improves the elapsed time spent for compiling the byte-code, e.g. for [plotly](https://build.opensuse.org/package/show/devel:languages:python:numeric/python-plotly) from *209 s* to *5 s* per flavor!

Speedup: Move compile loop to Python

---

flavor.in

python2 py_compile.compile function doesn't have the optimize parameter so we can't call it.

fix python2_compile macro

---

compile-macros.sh
default-prjconf

The first packages in the scientific python stack are dropping  support for Python 3.9:
https://scientific-python.org/specs/spec-0000/
https://github.com/ipython/ipython/pull/14254
Let's not get into introducing `%define skip_python39 1` for every jupyter and d:l:p:n package.

SPEC0: Drop python39, add python312 to buildset

---

macros/010-common-defs

The cpython patched returns the default paths based on /usr/local but for system packages it returns /usr when RPM_BUILD_ROOT variable is set.
https://src.fedoraproject.org/rpms/python3.12/blob/rawhide/f/00251-change-user-install-location.patch
Related opensuse bug: https://bugzilla.opensuse.org/show_bug.cgi?id=1225660

Make sure that RPM_BUILD_ROOT env is set

---

flavor.in
macros.lua

Escape the `\S` correctly to fix the regular expression when using the python_clone macro:
```
error: invalid syntax in lua script: [string "python_clone"]:9: invalid escape sequence near '"sed -ri "1s@#!.*python\S'
```
https://build.opensuse.org/package/live_build_log/openSUSE:Factory:Staging:C/avahi/standard/x86_64

Fix python_clone sed regex

---

flavor.in

This patch adds new flavored macros for pytest and pyunittest, so it's possible to use this macro without using subpackages, usually as %python3_pytest.
Fix https://github.com/openSUSE/python-rpm-macros/issues/170

Add %FLAVOR_pytest and %FLAVOR_pyunittest variants

---

flavor.in

`sed -i` breaks links, even if it's not replacing anything, so the usage of this script breaks all links in `/usr/bin` and `/usr/sbin` creating a copy of the files.
The `--follow-symlinks` options fixes this issue with `sed` so symlinks will be preserved.

Follow symlinks when replacing shebang with sed

---

flavor.in

In i586 sed fails when following symlinks to long paths, so changing to the target directory avoid this problem.
Follow up of this PR: https://github.com/openSUSE/python-rpm-macros/pull/186

Do sed in place

---

compile-macros.sh

python 3.8 is not used in any maintained distribution anymore. 3.14 is being introduced in Factory.

Drop python38, add python314
