macros/010-common-defs

Yet another attempt to write functional ``pytest`` and ``pytest_arch`` macros.
@mlschroe would you care to review, please?

Rewrite pytest and pytest_arch into Lua macros with multiple arguments.

---

README.md

Add mention of ``%pytest`` macro.
Fixes #27

Document %pytest in README.md

---

macros/010-common-defs

fix PYTHONPATH on %pytest_arch macro

---

macros/010-common-defs

Fixes #51, reverts part of #45

expand calls pyproject* macros

---

README.md

Enhance #54 by documenting the macros

add description for pyunittest macro

---

README.md

Document the changes of #64, #65, #67 and what is needed to pass #66
Resolve ambiguous use of pseudo- and shell variables and non-existent macro definitions: `$flavor` `%flavor`, `%modname` and so on are not universally defined.
Fixes #55

update README for multiple flavors

---

README.md
functions.lua
macros/010-common-defs

Fixes #5. Tested for python-Sphinx (https://github.com/openSUSE/python-rpm-macros/issues/66#issuecomment-721327326)

Introduce python_find_lang

---

macros/010-common-defs

More flavors means more dirs to ignore. Create the list dynamically.

pytest: ignore _build dirs for all flavors

---

macros.lua

Fixes https://github.com/openSUSE/python-rpm-macros/pull/81#issuecomment-738447146

fix print_provided_flavor again

---

README.md

Document python_module with boolean dependecies

---

macros/010-common-defs

Fixes https://github.com/openSUSE/python-rpm-macros/pull/94#issuecomment-768594339

dont't rename wheel when it already has the same name

---

macros.lua

We started to support [boolean dependencies](https://rpm.org/user_doc/boolean_dependencies.html) with `BuildRequires`, but the subpackage generator does not rewrite the flavors for runtime dependencies and capabilities. With this change, it is supported now.
IMHO it is a matter of taste if you want to write 
```spec
%if %{python_version_nodots} < 38
Requires: python-importlib-metadata
%endif
```
instead of
```spec
Requires: (python-importlib-metadata if python-base < 3.8)
```
But there are certainly use cases for flavor specific boolean dependencies in `Supplements:` and `Enhances:`, which could benefit from rewriting without the limitations of `packageand()`.
<hr />
Note that historically the default flavor is renamed as well. So a common pattern used for build dependencies does not work …

Support flavor rewriting of boolean runtime dependencies

---

compile-macros.sh

Step 4 of https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/message/CLJG47NPQAJNTGXES7HXWVA3D3UOYSIQ/

Add python310 flavor macros to compile set

---

macros/010-common-defs

hard-code %py_ver

---

macros/010-common-defs

print proper error on missing interpreter

---

macros/010-common-defs

See commit message and https://bugzilla.opensuse.org/show_bug.cgi?id=1201041.

Pass `--ignore-installed` to `pip install` in %pyproject_install

---

README.md
flavor.in
macros.lua
macros/010-common-defs

Fixes bsc#1198988
See https://discuss.python.org/t/pep-610-usage-guidelines-for-linux-distributions/4012

Avoid to install incorrect PEP610 metadata

---

README.md

`python36` does not exist anymore, so update the documentation

Update flavor sets in README

---

compile-macros.sh

Create python312 macros

---

default-prjconf

python38 was removed from Tumbleweed a while ago

remove python38

---

flavor.in
macros.lua

Fixes: https://github.com/openSUSE/python-rpm-macros/issues/175

don't eliminate any cmdline arguments in the shebang line

---

default-prjconf

Factory switched to python313, python310 is no longer in the buildset

Update default-prjconf for primary python: python313
